include themes/Batman.conf

# Enable remote control to do things like:
# kitty @ launch --location=vsplit --cwd=current 
allow_remote_control yes

# Shortcuts to open vsplit / hsplit window WITH current CWD
map ctrl+shift+enter launch --location=vsplit --cwd=current
map ctrl+shift+h launch --location=hsplit --cwd=current

# ---- Bell ----
enable_audio_bell no
command_on_bell canberra-gtk-play -i bell

# ---- Window ----
remember_window_size  yes
initial_window_width  640
initial_window_height 400

# ---- Font ----
font_size 11.5

# ---- Tabs ----
tab_bar_style powerline
tab_title_template "{index}: {title}"

# ---- Performance ----
scrollback_lines 10000
repaint_delay 8
input_delay 0

# ---- Tall Layout ----------
enabled_layouts tall:bias=60;full_size=1;mirrored=false,stack,grid

map ctrl+shift+l next_layout


map ctrl+[ layout_action decrease_num_full_size_windows
map ctrl+] layout_action increase_num_full_size_windows
map ctrl+/ layout_action mirror toggle
map ctrl+y layout_action mirror true
map ctrl+n layout_action mirror false

# Focus neighboring windows using arrow keys
map ctrl+shift+left  neighboring_window left
map ctrl+shift+right neighboring_window right
map ctrl+shift+up    neighboring_window up
map ctrl+shift+down  neighboring_window down

# change size using Ctrl+,
map ctrl+, layout_action bias 40 50 62 70 76 

################## coped from
# https://github.com/Vista1nik/i3-neon80s/tree/master

# font
font_family Inconsolata Bold for powerline
font_size 12.5

# special
foreground       #ffffff
foreground_bold  #ffffff
cursor           #ffffff
background       #181c30
background_opacity 1.0

# black
color0   #1b1d1e
color8   #505354

# red
color1   #f92672
color9   #ff5995

# green
color2   #82b414
color10  #b6e354

# yellow
color3   #fd971f
color11  #feed6c

# blue
color4   #0066cc
color12  #333399

# magenta
color5   #8c54fe
color13  #9e6ffe

# cyan
color6   #465457
color14  #899ca1

# white
color7   #ccccc6
color15  #f8f8f2
